### ISSUE TITLE
Trocar o PHP Query por outra biblioteca de manipulação DOM

### ISSUE THREAD

**Issue by marcioAlmada** [viniciusluiz/brasil-endereco#5]
O PHPQuery é uma biblioteca antiga e possui funções globais, declara constantes globais. Melhor usar uma biblioteca menos invasiva e com mais atividade recente da comunidade.

**Comment by viniciusluiz** [comment]
Por algum motivo apenas o PHPQuery conseguiu pegar as tabelas de dados retornada. Não sei ao certo qual o problema, pode ser tags em aberto ou qualquer outra coisa. 

Olhando no [packagist](https://packagist.org) encontrei a lib [symfony/dom-crawler](https://packagist.org/packages/symfony/dom-crawler) e partindo dela mudei o método HttpHelper::parseTable para o seguinte código que satisfaz o test

```
use Symfony\Component\DomCrawler\Crawler;

class HttpHelper
{
    public static function parseTable($html) {
        $tables = (new Crawler($html))->filterXPath('//table');
        return $tables->each(function ($table) {
            return $table->filterXPath('//td')->each(function($td) {
                return $td->text();
            });
        });
    }
...
```

Entretanto não obtive o resultado esperado para a página dos correios e mas, o mesmo comportamento observei ao usar a class DOMDocument do PHP.

É certo que o PHPQuery é uma biblioteca antiga toda via, consegue obter o resultado esperado deixado a desejar por outras bibliotecas mais ativas, mesmo assim, quem mudar a biblioteca PHPQuery conseguindo manter o [brasil-endereco](https://github.com/viniciusluiz/brasil-endereco) funcionando, é bem vindo.

;)
